name       : openshadinglanguage
version    : 1.12.8.0
release    : 16
source     :
    - https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/archive/refs/tags/v1.12.8.0.tar.gz : 4503d88f4ccf4283ab6ce4905c1dcf4bcb4e5e1ebf01ce9a2bc54a48ccfe02a7
homepage   : https://opensource.imageworks.com/osl.html
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : Advanced shading language for production GI renderers
description: |
    Open Shading Language (OSL) is a small but rich language for programmable shading in advanced renderers and other applications, ideal for describing materials, lights, displacement, and pattern generation.
clang      : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - libboost-devel
    - numpy
    - partio-devel
    - pybind11
rundeps    :
    - numpy
setup      : |
    %cmake_ninja -DCMAKE_CXX_STANDARD=14
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
