name       : openshadinglanguage
version    : 1.11.10.0
release    : 3
source     :
    - https://github.com/imageworks/OpenShadingLanguage/archive/Release-1.11.10.0.tar.gz : e60b049b666f7eff519a64608ca166946c3de5db49515a36d379837f82310f05
homepage   : https://opensource.imageworks.com/osl.html
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : Advanced shading language for production GI renderers
description: |
    Open Shading Language (OSL) is a small but rich language for programmable shading in advanced renderers and other applications, ideal for describing materials, lights, displacement, and pattern generation.
clang      : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - libboost-devel
    - numpy
    - partio-devel
    - pybind11
rundeps    :
    - numpy
setup      : |
    %cmake_ninja -DCMAKE_CXX_STANDARD=14
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
