name       : openshadinglanguage
version    : 1.11.14.2
release    : 4
source     :
    - https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/archive/refs/tags/v1.11.14.2.tar.gz : 6dea570686740a5d5c81e595020f3fef5b8af7201a95460024c17297fb7eb718
homepage   : https://opensource.imageworks.com/osl.html
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : Advanced shading language for production GI renderers
description: |
    Open Shading Language (OSL) is a small but rich language for programmable shading in advanced renderers and other applications, ideal for describing materials, lights, displacement, and pattern generation.
clang      : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - libboost-devel
    - numpy
    - partio-devel
    - pybind11
rundeps    :
    - numpy
setup      : |
    %cmake_ninja -DCMAKE_CXX_STANDARD=14
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
